# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3bf29a5c3ee28bc91c5df961bbfd370181fe527eea62c7425b1fae8a40abe442c9754d441e595d376bb1d59bd5a86cc280d066e8290ea39a8ec2ea64c738052

test:
  secret_key_base: 63c222bd82a210912f6160d92a1273ed6d45517d6b128cbd6959e536b367fda07236787675f528ac65e3565f8608d23d4354cd354cb1be8165b3f20021668f44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
